# Generated by Django 4.2 on 2023-04-10 13:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BangThietKeDiemSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ky_hoc', models.CharField(max_length=10)),
                ('giua_ki', models.FloatField()),
                ('cuoi_ki', models.FloatField()),
                ('cac_cot_diem_them', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.JSONField(default=dict)),
                ('ky_hoc', models.CharField(max_length=10)),
                ('bang_thiet_ke_diem_so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.bangthietkediemso')),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_gv', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=10, unique=True)),
                ('ten_lop', models.CharField(max_length=120, unique=True)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoc_giang_day', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=10, unique=True)),
                ('bang_thiet_ke_diem_so', models.ManyToManyField(related_name='sinh_viens', through='manangepoints.DiemSo', to='manangepoints.bangthietkediemso')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinh_viens', to='manangepoints.lophoc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=10, unique=True)),
                ('ten_mon', models.CharField(max_length=50)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='FileCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv/')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.lophoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.sinhvien')),
            ],
        ),
        migrations.AddField(
            model_name='diemso',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.sinhvien'),
        ),
        migrations.AddField(
            model_name='bangthietkediemso',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_thiet_ke_diem_so', to='manangepoints.monhoc'),
        ),
        migrations.AddField(
            model_name='bangthietkediemso',
            name='sinh_vien',
            field=models.ManyToManyField(related_name='mon_hoc', through='manangepoints.DiemSo', to='manangepoints.sinhvien'),
        ),
        migrations.AlterUniqueTogether(
            name='diemso',
            unique_together={('sinh_vien', 'bang_thiet_ke_diem_so')},
        ),
    ]
