# Generated by Django 4.2 on 2023-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/%Y/%m'),
        ),
    ]
