# Generated by Django 4.2 on 2023-04-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0003_alter_sinhvien_bang_thiet_ke_diem_so_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ghi_chu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('start_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='diemso',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='bang_thiet_ke_diem_so',
        ),
        migrations.AlterField(
            model_name='diemso',
            name='diem',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='giang_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_hoc_giang_day', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='giang_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manangepoints.giangvien'),
        ),
        migrations.CreateModel(
            name='BangThietKeMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.cotdiem')),
                ('giang_vien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giang_vien', to='manangepoints.giangvien')),
                ('ky_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manangepoints.hocky')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_thiet_ke_diem_so', to='manangepoints.monhoc')),
            ],
        ),
        migrations.RemoveField(
            model_name='diemso',
            name='bang_thiet_ke_diem_so',
        ),
        migrations.RemoveField(
            model_name='diemso',
            name='ky_hoc',
        ),
        migrations.AddField(
            model_name='diemso',
            name='bang_thiet_ke_mon_hoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manangepoints.bangthietkemonhoc'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='cot_diem',
            field=models.ManyToManyField(related_name='mon_hoc', through='manangepoints.BangThietKeMonHoc', to='manangepoints.cotdiem'),
        ),
        migrations.DeleteModel(
            name='BangThietKeDiemSo',
        ),
    ]
