# Generated by Django 4.2 on 2023-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0005_alter_customuser_options_customuser_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/static/users/defaultAvatar.jpg', upload_to='users/%Y/%m'),
        ),
    ]
