# Generated by Django 4.2 on 2023-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0007_remove_customuser_active_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/%Y/%m'),
        ),
    ]
