# Generated by Django 4.2 on 2023-04-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0009_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangthietkemonhoc',
            name='cot_diem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manangepoints.cotdiem'),
        ),
    ]
