# Generated by Django 4.2 on 2023-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0011_alter_diemso_diem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemso',
            name='diem',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
