# Generated by Django 4.2 on 2023-04-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manangepoints', '0012_alter_diemso_diem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='giang_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_hoc_giang_day', to='manangepoints.giangvien'),
        ),
    ]
